<p> <center><span style="font-size: 2em; color: red; ">ATENCIÓN- INGRESO NO PERMITIDO</center>
<br>
<p> - HA ACCEDIDO A ESTE MODULO DE MANERA INDEBIDA O NO TIENE PERMISOS PARA INGRESAR A ESTE.
<p> - SI ES UN USUARIO CON PERMISOS Y ESTÁ LEYENDO ESTO COMUNIQUESE CON EL ADMINISTRADOR DEL SISTEMA PARA SLUCIONAR EL PROBLEMA.